---
- name: Install Monit
  pacman: name=monit

- name: Update Monit configuration
  template: src=monitrc.j2
            dest=/etc/monit/monitrc
            owner=root
            group=root
            mode=700
  notify: Restart Monit
