---
- name: Warn users if the server's Linux distribution is not Ubuntu 14.04
  pause: prompt="Ubuntu 14.04 is the only officially supported distribution; the setup will probably fail. Press Enter if you still want to continue."
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version != "14"

# Set default variables
- include: set-default-variables.yml

- name: Copy the HTML header and footer templates that are used during documentation generation
  copy: src={{ item.src }}
        dest={{ item.dest }}
  with_items:
    - { src: "header.html", dest: "{{ streisand_header_template }}" }
    - { src: "footer.html", dest: "{{ streisand_footer_template }}" }
