---
streisand_common_packages:
  # Used to compile Libreswan and OpenConnect Server (ocserv)
  - build-essential
  # Used to perform API requests, including the version check for
  # the Tor Browser Bundle
  - curl
  # Used to verify GPG signatures for mirrored packages
  - gnupg
  # Used to configure firewall rules
  - iptables
 

streisand_gateway_location: "/var/www/streisand"

streisand_local_directory: "generated-docs"

streisand_header_template: "/tmp/header.html"
streisand_footer_template: "/tmp/footer.html"
